### PR TITLE
Revert "Sound files corrections"

### PR DESCRIPTION
**Pull request by HerbyW**
Reverts HerbyW/Antonov-An-12#2

### CODE REVIEW

**Comment by IAHM-COL** [comment]
Hi HerbyW
Do you want the files to remain stereo?
FGFS sound engines do not understand this format!
Best
IH-COL

**Comment by HerbyW** [comment]
Am Samstag, 9. Mai 2015, 14:37:43 schrieb Israel Hernandez:
> Hi HerbyW
> Do you want the files to remain stereo?
> FGFS sound engines do not understand this format!
> Best
> IH-COL
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HerbyW/Antonov-An-12/pull/3#issuecomment-100551472

Yes. And no more changes to my repository please.
I want it like Jwocky, so that they are forked from mine and not the other 
way. I can not look to your changes, i have to do other things.
And for sound files it is clear that stereo not works in FG, but if you want to 
have a stereo sound in the cockpit you need 2 mono sounds and therefore you 
need the stereo sound.
-- 
--
-
Schamanenzentrum Musikhimmel
Ritual Musik Schule
Polierte Keramik

Herbert Wagner
Am Schwalbanger 40
86633 Neuburg Donau

Telefon 0049 / 0 84 31 - 64 85 329

Homepage: http://www.superschaman.de
Youtube:     http://www.youtube.com/user/SuperShamanDotCom
Skype:        schaman.herby
Facebook:  http://www.facebook.com/schaman.gerbert
Xing:           https://www.xing.com/profile/Herby_Wagner

**Comment by IAHM-COL** [comment]
Ok --no more changes to your repo.
the direction of the fork makes no difference what so ever. 
Will not insist on the stereo files. 
Feel free to revert.

stereo produces no sound in FG. But if that is what you intend, it is fine for me ;) 

Are you confortable reverting or need help?

**Comment by HerbyW** [comment]
Am Samstag, 9. Mai 2015, 14:59:03 schrieb Israel Hernandez:
> Ok --no more changes to your repo.
> the direction of the fork makes no difference what so ever.
> Will not insist on the stereo files.
> Feel free to revert.
> 
> stereo produces no sound in FG. But if that is what you intend, it is fine
> for me ;)
> 
> Are you confortable reverting or need help?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HerbyW/Antonov-An-12/pull/3#issuecomment-100552551

I do not know how to do it, so i deleted everything and pushed again, but i do 
not know if the user gets noe the latest version or not, i am confused.

-- 
--
-
Schamanenzentrum Musikhimmel
Ritual Musik Schule
Polierte Keramik

Herbert Wagner
Am Schwalbanger 40
86633 Neuburg Donau

Telefon 0049 / 0 84 31 - 64 85 329

Homepage: http://www.superschaman.de
Youtube:     http://www.youtube.com/user/SuperShamanDotCom
Skype:        schaman.herby
Facebook:  http://www.facebook.com/schaman.gerbert
Xing:           https://www.xing.com/profile/Herby_Wagner

**Comment by IAHM-COL** [comment]
yes. that works. 
If you commit again. And push again, user will get all your changes.

**Comment by HerbyW** [comment]
I realy want my repository be mine, so that i can make changes to it and the 
users get the latest version from me.
So, forking from mine you can do but if i have to take care about the 
fgmembers reprository it is not comfortable for me.

So, in a few days i have new names for every airplane and then we can make the 
change.

Am Samstag, 9. Mai 2015, 14:59:03 schrieb Israel Hernandez:
> Ok --no more changes to your repo.
> the direction of the fork makes no difference what so ever.
> Will not insist on the stereo files.
> Feel free to revert.
> 
> stereo produces no sound in FG. But if that is what you intend, it is fine
> for me ;)
> 
> Are you confortable reverting or need help?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/HerbyW/Antonov-An-12/pull/3#issuecomment-100552551

-- 
--
-
Schamanenzentrum Musikhimmel
Ritual Musik Schule
Polierte Keramik

Herbert Wagner
Am Schwalbanger 40
86633 Neuburg Donau

Telefon 0049 / 0 84 31 - 64 85 329

Homepage: http://www.superschaman.de
Youtube:     http://www.youtube.com/user/SuperShamanDotCom
Skype:        schaman.herby
Facebook:  http://www.facebook.com/schaman.gerbert
Xing:           https://www.xing.com/profile/Herby_Wagner

**Comment by IAHM-COL** [comment]
sure. We can do that.
to be the master branch the airplane need new plane... that's all

That way your repo will be isolated from helijah's

**Comment by IAHM-COL** [comment]
you do not need to take care of FGMEMBERs repo if you do not want to.

**Comment by IAHM-COL** [comment]
Only the Antonov-12 and Antonov-22 need change. The AN225 and the shuttle dont need new names.

**Pull request merged**
